### ISSUE TITLE
Support for IntelliJ 2021.3

### ISSUE THREAD

**Issue by ondrejfuhrer** [grafana/k6-intellij-plugin#10]
Hello team,

new IntelliJ version has been released and the plugin doesn't seem to support it. Can we get a new version? 

```
Plugin 'k6' (version '0.2.2') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is IU-213.5744.223
```

**Comment by mbolotov** [comment]
Hi @ondrejfuhrer!
I've uploaded the new version. It will be available once JetBrains approve it.

**Comment by ondrejfuhrer** [comment]
Thank you @mbolotov I see new version available 🙂  🎖️
