### ISSUE TITLE
k6 plugin is not supported in IntelliJ IDEA 2021.2.1

### ISSUE THREAD

**Issue by ondrejfuhrer** [grafana/k6-intellij-plugin#7]
Right now the plugin isn't supported. 

IntelliJ Version: 2021.2.1

![ScreenCapture at Fri Sep 10 16:35:06 CEST 2021](https://user-images.githubusercontent.com/10830505/132870746-934bc1f9-674d-4188-a277-53e42cf9839a.png)

Would be great if we get new version that will support latest version of the IDE.

**Comment by ppcano** [comment]
Please, @ondrejfuhrer, let us know if the [latest version](https://plugins.jetbrains.com/plugin/16141-k6/versions/stable/136566) has fixed this issue.

**Comment by ondrejfuhrer** [comment]
Hey @ppcano , yes, thank you! 

All is working well now, also with the latest `2021.2.2` version.
